name: ğŸš€ Ship it to npm!

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: ğŸ› Checkout the code (no stealing!)
        uses: actions/checkout@v5

      - name: ğŸª„ Setup Node.js (abracadabra!)
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - name: ğŸ• Install dependencies (snack time for npm)
        run: npm ci

      - name: ğŸ”¨ Build all packages (make it shine)
        run: npm run build

      - name: ğŸ§ª Run tests (mad scientist mode)
        run: npm test

      - name: ğŸ“¦ Publish @eusilvio/cep-lookup (send it to the wild!)
        run: npm publish --access public --provenance --ignore-scripts -w @eusilvio/cep-lookup
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: ğŸ¯ Publish @eusilvio/cep-lookup-react (React rocket launch!)
        run: npm publish --access public --provenance --ignore-scripts -w @eusilvio/cep-lookup-react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: ğŸ§ª Publish @eusilvio/cep-lookup-vue (Vue spaceship launch!)
        run: npm publish --access public --provenance --ignore-scripts -w @eusilvio/cep-lookup-vue
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
